### ISSUE TITLE
ImportError: cannot import name '_DataLoaderIter'

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [aamir-mustafa/super-resolution-adversarial-defense#3]
Hello! I have created the python 3.6,why this error still occured.

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "D:\Graduate\super-resolution-adversarial-defense-master\src\data\__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "D:\Graduate\super-resolution-adversarial-defense-master\src\dataloader.py", line 13, in <module>
    from torch.utils.data.dataloader import _DataLoaderIter
ImportError: cannot import name '_DataLoaderIter'

**Comment by aamir-mustafa** [comment]
The implementation is for PyTorch version 0.4.1
Kindly change your PyTorch version accordingly. If not, you can try removing the prefix "underscore" (_) from _DataLoaderIter to DataLoaderIter.

**Comment by zhjikoshlizhzc** [comment]
When I try to run sh super_resolution.sh,there is new error occured.

(pytorch) D:\Graduate\super-resolution-adversarial-defense-master\src>sh super_resolution.sh
Making model...
Download the model

Evaluation:
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    while not t.terminate():
  File "D:\Graduate\super-resolution-adversarial-defense-master\src\trainer.py", line 139, in terminate
    self.test()
  File "D:\Graduate\super-resolution-adversarial-defense-master\src\trainer.py", line 83, in test
    if self.args.save_results: self.ckp.begin_background()
  File "D:\Graduate\super-resolution-adversarial-defense-master\src\utility.py", line 141, in begin_background
    for p in self.process: p.start()
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'checkpoint.begin_background.<locals>.bg_target'

(pytorch) D:\Graduate\super-resolution-adversarial-defense-master\src>Making model...
Download the model

Evaluation:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Graduate\super-resolution-adversarial-defense-master\src\main.py", line 26, in <module>
    while not t.terminate():
  File "D:\Graduate\super-resolution-adversarial-defense-master\src\trainer.py", line 139, in terminate
    self.test()
  File "D:\Graduate\super-resolution-adversarial-defense-master\src\trainer.py", line 83, in test
    if self.args.save_results: self.ckp.begin_background()
  File "D:\Graduate\super-resolution-adversarial-defense-master\src\utility.py", line 141, in begin_background
    for p in self.process: p.start()
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\acer\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by nanmehta** [comment]
i have checked by removing the undercore but it is still not working
