### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by le000043** [aamir-mustafa/super-resolution-adversarial-defense#8]
Hello, I encountered this error while attempting to run your super_resolution.sh code
````Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "/content/super-resolution-adversarial-defense/src/data/__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "/content/super-resolution-adversarial-defense/src/dataloader.py", line 10, in <module>
    from torch._C import _set_worker_signal_handlers, _update_worker_pids, \
ImportError: cannot import name '_update_worker_pids' from 'torch._C' (/usr/local/lib/python3.7/dist-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so)

**Comment by aamir-mustafa** [comment]
Hi,
The problem could be that you are using the Pytorch 1.1 or above.
You may want to uninstall that and built PyTorch v1.0.0 (or lower) from source again and hopefully it will work. 
Hope that helps
