### ISSUE TITLE
Can't run the examples

### ISSUE THREAD

**Issue by le000043** [aamir-mustafa/super-resolution-adversarial-defense#9]
my PyTorch version is 1.0.0 and version torchvision is 0.2.1
````
$python main.py --data_test Demo --scale 2 --pre_train download --test_only --save_results
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "/content/super-resolution-adversarial-defense/src/data/__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "/content/super-resolution-adversarial-defense/src/dataloader.py", line 17, in <module>
    from torch.utils.data.dataloader import _worker_manager_loop
ImportError: cannot import name '_worker_manager_loop' from 'torch.utils.data.dataloader' (/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py)

**Comment by Haiboz0105** [comment]
The same problem, I've tried many torch versions, but still didn't work.
